export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COMMUNITIES_SUCCESS = 'LOAD_COMMUNITIES_SUCCESS';
export const CREATE_COMMUNITIES_SUCCESS = 'CREATE_COMMUNITIES_SUCCESS';
export const UPDATE_COMMUNITIES_SUCCESS = 'UPDATE_COMMUNITIES_SUCCESS';

export const LOAD_VISITS_SUCCESS = 'LOAD_VISITS_SUCCESS';
export const CREATE_VISITS_SUCCESS = 'CREATE_VISITS_SUCCESS';
export const UPDATE_VISITS_SUCCESS = 'UPDATE_VISITS_SUCCESS';

export const LOAD_INCIDENTS_SUCCESS = 'LOAD_INCIDENTS_SUCCESS';
export const CREATE_INCIDENTS_SUCCESS = 'CREATE_INCIDENTS_SUCCESS';
export const UPDATE_INCIDENTS_SUCCESS = 'UPDATE_INCIDENTS_SUCCESS';

export const LOAD_VISITORS_SUCCESS = 'LOAD_VISITORS_SUCCESS';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_VISITORS_SUCCESS = 'CREATE_VISITORS_SUCCESS';
export const UPDATE_VISITORS_SUCCESS = 'UPDATE_VISITORS_SUCCESS';
export const CREATE_COURSES_SUCCESS = 'CREATE_AUTHORS_SUCCESS';
export const UPDATE_COURSES_SUCCESS = 'UPDATE_AUTHORS_SUCCESS';

